[package]
name = "precompute"
version = "0.1.0"
edition = "2024"

[dependencies]
dashu = { version = "0.4", features = ["num-traits"] }
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.117"
num-traits = "0.2.19"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
